

model:
  provider: openai
  name: gpt-4o
  api_key: "${OPENAI_API_KEY}"  

agent:
  name: anus
  mode: auto
  max_iterations: 10
  memory_capacity: 2000
  verbose: true

tools:
  enabled:
    - calculator
    - search
    - text
    - code

logging:
  level: DEBUG
  file: logs/anus.log 