model:
  provider: openai
  name: gpt-4o
  max_tokens: 1500 
  api_key: "${OPENAI_API_KEY}"  

agent:
  name: seeker-o1
  mode: multi
  max_iterations: 10
  memory_capacity: 2000
  verbose: true

tools:
  enabled:
    - calculator
    - search
    - text
    - code

logging:
  level: DEBUG
  file: logs/seeker-o1.log 