# ANUS Configuration File

model:
  provider: openai
  name: gpt-4o
  max_tokens: 1500  # Limit token output to reduce rate limit issues
  api_key: "${OPENAI_API_KEY}"  # Uses the environment variable you set

agent:
  name: anus
  mode: multi
  max_iterations: 10
  memory_capacity: 2000
  verbose: true

tools:
  enabled:
    - calculator
    - search
    - text
    - code

logging:
  level: DEBUG
  file: logs/anus.log 